name: Copy File Between Branches

on:
  workflow_dispatch: # Trigger manually

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Switch to the source branch
      - name: Switch to source branch
        run: |
          git fetch origin
          git checkout feature/workflow

      # Step 3: Copy the file
      - name: Copy file
        run: |
          cp demo/kl.txt ./sample/kl.txt

      # Step 4: Switch to the target branch
      - name: Switch to target branch
        run: |
          git checkout dev

      # Step 5: Add and commit the changes
      - name: Commit changes
        run: |
          git add ./testing/sample/
          git commit -m "Copy file from source branch to target branch"
          git push origin dev
